/**
 * Metal Casting Project API
 * This API serves the frontend with data from databases and other external services.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientRegistrationRequestModel { 
    contactName?: string | null;
    contactSurname?: string | null;
    title?: string | null;
    gender?: string | null;
    contactEmail?: string | null;
    contactNumber?: string | null;
    avatar?: string | null;
    companyName?: string | null;
    companyRegistrationNumber?: string | null;
    isCompanyPresent?: boolean;
    companyProfile?: string | null;
}

