/**
 * Metal Casting Project API
 * This API serves the frontend with data from databases and other external services.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnquiryResponseModel { 
    id?: number;
    focusArea?: number;
    enquiry_date?: string;
    quarter?: string | null;
    company?: string | null;
    companyRegistrationNumber?: string | null;
    description?: string | null;
    serviceTech?: number;
    socioEconomicImpact?: number;
    productExpectation?: number;
    projectBudget?: number;
    expectedCompletion?: string;
}

