/**
 * Metal Casting Project API
 * This API serves the frontend with data from databases and other external services.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnquiryRequestModel { 
    id?: number;
    focus_area_fk?: number;
    enquiry_date?: string;
    quarter?: string | null;
    company?: string | null;
    company_registration_number?: string | null;
    description?: string | null;
    service_tech_fk?: number;
    socio_economic_impact_fk?: number;
    product_expectation_fk?: number;
    project_budget?: number;
    expected_completion?: string;
}

