/**
 * Metal Casting Project API
 * This API serves the frontend with data from databases and other external services.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvoiceRequestModel { 
    id?: number;
    reference?: string | null;
    invoice_date?: string;
    date_due?: string;
    title?: string | null;
    description?: string | null;
    vat_number?: string | null;
    bill_to_id?: number;
    vat?: string | null;
    terms?: string | null;
    total?: number;
    subtotal?: number;
    quantity?: number;
    total_due?: number;
    user_id?: number;
}

