/**
 * Metal Casting Project API
 * This API serves the frontend with data from databases and other external services.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectProgressResponseModel { 
    projectNumber?: string | null;
    targetStartDate?: string;
    targetEndDate?: string;
    actualStartDate?: string;
    actualEndDate?: string;
    projectStatus?: string | null;
    progressUpdatePercentage?: number;
    startedQuarter?: string | null;
    currentQuarter?: string | null;
    endingQuarter?: string | null;
    projectDuration?: number;
}

