export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './clientsReports.service';
import { ClientsReportsService } from './clientsReports.service';
export * from './employees.service';
import { EmployeesService } from './employees.service';
export * from './employeesReports.service';
import { EmployeesReportsService } from './employeesReports.service';
export * from './enquiry.service';
import { EnquiryService } from './enquiry.service';
export * from './genericServices.service';
import { GenericServicesService } from './genericServices.service';
export * from './invoice.service';
import { InvoiceService } from './invoice.service';
export * from './mctsKpiReports.service';
import { MctsKpiReportsService } from './mctsKpiReports.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './projectExpenditure.service';
import { ProjectExpenditureService } from './projectExpenditure.service';
export * from './projectProgress.service';
import { ProjectProgressService } from './projectProgress.service';
export * from './projectTodos.service';
import { ProjectTodosService } from './projectTodos.service';
export * from './projects.service';
import { ProjectsService } from './projects.service';
export * from './quarters.service';
import { QuartersService } from './quarters.service';
export * from './quotation.service';
import { QuotationService } from './quotation.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [ClientsService, ClientsReportsService, EmployeesService, EmployeesReportsService, EnquiryService, GenericServicesService, InvoiceService, MctsKpiReportsService, PaymentService, ProductsService, ProjectExpenditureService, ProjectProgressService, ProjectTodosService, ProjectsService, QuartersService, QuotationService, UsersService];
